Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Creates algebraic symbols that can be used in an algebraic expression
@variables g, r, x0
G = (1 + g)
R = (1 + r)
p0 = x0 / (1 - G * R ^ (-1))
print("Our formula is")
latexify(p0) |> s -> render(s, MIME("image/png"))
------------------

failed process: Process(`[4mlualatex[24m [4m--interaction=batchmode[24m [4m/tmp/jl_Mjy3wFMZkt.tex[24m`, ProcessExited(1)) [1]


Stacktrace:
  [1] pipeline_error
    @ ./process.jl:565 [inlined]
  [2] run(::Base.CmdRedirect; wait::Bool)
    @ Base ./process.jl:480
  [3] run
    @ ./process.jl:477 [inlined]
  [4] #142
    @ ~/.julia/packages/Latexify/wTEwj/src/utils.jl:108 [inlined]
  [5] cd(f::Latexify.var"#142#143"{Bool, String}, dir::String)
    @ Base.Filesystem ./file.jl:112
  [6] render(s::LaTeXString, ::MIME{Symbol("application/pdf")}; debug::Bool, name::String, open::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Latexify ~/.julia/packages/Latexify/wTEwj/src/utils.jl:105
  [7] render(s::LaTeXString, ::MIME{Symbol("image/png")}; debug::Bool, convert::Symbol, name::String, callshow::Bool, open::Bool, dpi::Int64, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Latexify ~/.julia/packages/Latexify/wTEwj/src/utils.jl:174
  [8] render
    @ ~/.julia/packages/Latexify/wTEwj/src/utils.jl:152 [inlined]
  [9] #1
    @ ./In[7]:7 [inlined]
 [10] |>(x::LaTeXString, f::var"#1#2")
    @ Base ./operators.jl:911
 [11] top-level scope
    @ In[7]:7
LoadError: failed process: Process(`[4mlualatex[24m [4m--interaction=batchmode[24m [4m/tmp/jl_Mjy3wFMZkt.tex[24m`, ProcessExited(1)) [1]


